# -*- python -*-

srcdir= '.'
blddir= '../bin'

def build(bld):
    bld.stlib(
        source = ['gtest/gtest-all.cpp',
                  'gtest/gtest_main.cc'],
        target = 'gtest',
        includes = '.',
    )

    bld.stlib(
        source = ['gflags/gflags.cc',
                  'gflags/gflags_completions.cc',
                  'gflags/gflags_reporting.cc'],
        target = 'gflags',
        includes = '.',
    )
